import os
import shutil
import queue
import traceback
import numpy as np
import threading
import atexit
import signal

from pathlib import Path
from datetime import datetime
from concurrent.futures import ThreadPoolExecutor

from .adapter import ModelAdapter
from .config.loader import load_config
from .reporting.reporter import RunReporter
from .errors import RunError


class SimModel:
    def __init__(self, cfgPath: str):
        self.cfgPath = cfgPath
        self._closed = False
        self._cleanup_lock = threading.Lock()
        self._cleanup_done = False

        self.cfg = load_config(cfgPath)

        self.create_run_queue()

        # Build adapter (aggregates all components)
        self.adapter = ModelAdapter(self.cfg, self.backupPath)

        # Parameter and evaluation metadata
        self.nInput, self.xLabels, self.varType, self.varSet, self.ub, self.lb = (
            self.adapter.get_param_info()
        )
        self.nOutput, self.optType, self.nConstraints = (
            self.adapter.get_evaluation_info()
        )
        self.optSign = [1 if s == "min" else -1 for s in self.optType]

        # Reporter
        pLabels = []
        if self.cfg.parameters.transformer:
            pLabels = [p.name for p in self.cfg.parameters.physical]
        self.reporter = RunReporter(self.backupPath, self.xLabels, pLabels, self.cfg)
        self.reporter.start()

        atexit.register(self._cleanup_on_exit)
        try:
            signal.signal(signal.SIGINT, self._handle_termination)
            signal.signal(signal.SIGTERM, self._handle_termination)
        except Exception:
            pass

    def create_run_queue(self):
        now = datetime.now()
        base_time_str = now.strftime("%m%d_%H%M%S")
        self.runPath = os.path.join(self.cfg.basic.workPath, "tempRun", base_time_str)
        counter = 0
        while os.path.exists(self.runPath):
            micro_str = f"{now.microsecond + counter:06d}"
            self.runPath = os.path.join(self.cfg.basic.workPath, "tempRun", base_time_str + "_" + micro_str)
            counter += 1
        os.makedirs(self.runPath, exist_ok=True)

        self.runQueue = queue.Queue()
        for i in range(self.cfg.basic.parallel):
            path = os.path.join(self.runPath, f"instance_{i}")
            shutil.copytree(self.cfg.basic.projectPath, path)
            self.runQueue.put(path)

        self.backupPath = os.path.join(self.runPath, "backup")
        os.makedirs(self.backupPath, exist_ok=True)
        shutil.copy(self.cfgPath, self.backupPath)
        # Backup resolved general config if it exists (generated by template mode)
        cfg_file = Path(self.cfgPath).resolve()
        resolved_path = cfg_file.parent / (cfg_file.stem + "_general.yaml")
        if resolved_path.exists():
            shutil.copy(resolved_path, self.backupPath)
        for series in self.cfg.series:
            if series.obs:
                obs_src = os.path.join(self.cfg.basic.workPath, series.obs.file)
                if os.path.exists(obs_src):
                    shutil.copy(obs_src, self.backupPath)

    def _to_float_or_nan(self, value):
        if value is None:
            return np.nan
        if hasattr(value, "item"):
            try:
                return float(value.item())
            except Exception:
                pass
        arr = np.asarray(value)
        if arr.size == 0:
            return np.nan
        if arr.size == 1:
            return float(arr.reshape(-1)[0])
        return np.nan

    def _objective_penalty(self, j):
        return np.inf * self.optSign[j]

    def _constraint_penalty(self):
        return np.inf

    def evaluate(self, X):
        n = X.shape[0]
        n_obj = self.adapter.evaluator.nOutput
        n_con = self.adapter.evaluator.nConstraints

        objs = np.zeros((n, n_obj))
        cons = np.full((n, n_con), self._constraint_penalty()) if n_con > 0 else None

        batch_id = self.reporter.newBatchId()
        records = []

        if self.cfg.basic.parallel > 1:
            with ThreadPoolExecutor(max_workers=self.cfg.basic.parallel) as executor:
                futures = [
                    executor.submit(self._subprocess, X[i, :], i, batch_id)
                    for i in range(n)
                ]
                records = [future.result() for future in futures]
        else:
            for i in range(n):
                records.append(self._subprocess(X[i, :], i, batch_id))

        for rec in records:
            i = int(rec["i"])
            for j, obj_id in enumerate(self.cfg.objectives.use):
                val = self._to_float_or_nan(rec.get(obj_id, np.nan))
                if np.isnan(val):
                    val = self._objective_penalty(j)
                objs[i, j] = val
            if cons is not None:
                for j, con_id in enumerate(self.cfg.constraints.use):
                    val = self._to_float_or_nan(rec.get(con_id, np.nan))
                    if np.isnan(val):
                        val = self._constraint_penalty()
                    cons[i, j] = val

        return {"objs": objs, "cons": cons}

    def _subprocess(self, X, i, batch_id):
        workPath = self.runQueue.get()
        context = {
            "X": np.asarray(X).ravel(),
            "i": int(i),
            "batch_id": int(batch_id),
            "warnings": [],
        }
        try:
            self.adapter.write_params(workPath, X, context)
            context["P"] = self.adapter.get_physical_params(X)
            self.adapter.run_model(workPath)
            context = self.adapter.read_results(workPath, context)
            if "warnings" not in context:
                context["warnings"] = []
            scalars = self.adapter.evaluate(context)
            context.update(scalars)
        except RunError as e:
            context["error"] = {
                "stage": e.stage, "code": e.code,
                "target": e.target, "message": e.message,
                "severity": "fatal", "traceback": e.traceback,
            }
        except Exception as e:
            context["error"] = {
                "stage": "unknown", "code": "UNEXPECTED_EXCEPTION",
                "target": "simulation", "message": str(e),
                "severity": "fatal", "traceback": traceback.format_exc(),
            }
        finally:
            self.runQueue.put(workPath)
            if "error" in context:
                self._error_handler(context, self.cfg)
            if hasattr(self, "reporter") and self.reporter is not None:
                try:
                    self.reporter.submit(context)
                except RuntimeError:
                    pass
        return context

    def _error_handler(self, context, cfg):
        for obj_id in cfg.objectives.use:
            context[obj_id] = cfg.objectives.items[obj_id].on_error
        for con_id in cfg.constraints.use:
            context[con_id] = cfg.constraints.items[con_id].on_error
        for diag_id in cfg.diagnostics.use:
            context[diag_id] = cfg.diagnostics.items[diag_id].on_error

    # close and exit
    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
        return False

    def close(self):
        if getattr(self, "_closed", False):
            return
        self._closed = True
        if hasattr(self, "reporter") and self.reporter is not None:
            try:
                self.reporter.close()
            except Exception as e:
                print(f"[SimModel.close] reporter.close() failed: {e}")
        try:
            self._cleanup_instances()
        except Exception as e:
            print(f"[SimModel.close] instance cleanup failed: {e}")
            print("Please clean instance folders manually if needed.")

    def __del__(self):
        try:
            self.close()
        except Exception:
            pass

    def _cleanup_instances(self):
        if not hasattr(self, "runPath") or not self.runPath:
            return
        with self._cleanup_lock:
            if self._cleanup_done:
                return
            failed = []
            try:
                for name in os.listdir(self.runPath):
                    full_path = os.path.join(self.runPath, name)
                    if not os.path.isdir(full_path):
                        continue
                    if name == "backup":
                        continue
                    if name.startswith("instance_"):
                        try:
                            shutil.rmtree(full_path)
                        except Exception as e:
                            failed.append((full_path, str(e)))
            finally:
                self._cleanup_done = True
            if failed:
                print("[SimModel.cleanup] Failed to remove some instance folders:")
                for path, err in failed:
                    print(f"  - {path}: {err}")
                print("Please remove them manually if needed.")

    def _cleanup_on_exit(self):
        try:
            self.close()
        except Exception as e:
            print(f"[SimModel._cleanup_on_exit] cleanup failed: {e}")

    def _handle_termination(self, signum, frame):
        try:
            print(f"[SimModel] Received signal {signum}, cleaning instance folders...")
            self.close()
        except Exception as e:
            print(f"[SimModel._handle_termination] cleanup failed: {e}")
        raise SystemExit(128 + signum)
